export const projects = [
    {
        id: 0,
        name: 'Quizzical',
        previewImg: 'project1.png',
        link: 'https://poitrew.github.io/quizzical/',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam harum dignissimos, ipsa aspernatur assumenda perspiciatis tempore vero quas non! Commodi itaque, vero inventore assumenda voluptates in repudiandae non voluptatibus eum.',
        time: 2022,
        techs: ['React', 'React hooks', 'Trivia API', 'HTML & CSS'],
    },
    {
        id: 1,
        name: 'Thand Dat blog',
        previewImg: 'project1.png',
        link: 'https://poitrew.github.io/quizzical/',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam harum dignissimos, ipsa aspernatur assumenda perspiciatis tempore vero quas non! Commodi itaque, vero inventore assumenda voluptates in repudiandae non voluptatibus eum.',
        time: 2022,
        techs: ['React', 'React hooks'],
    },
    {
        id: 2,
        name: 'Tetris',
        previewImg: 'project1.png',
        link: 'https://poitrew.github.io/quizzical/',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam harum dignissimos, ipsa aspernatur assumenda perspiciatis tempore vero quas non! Commodi itaque, vero inventore assumenda voluptates in repudiandae non voluptatibus eum.',
        time: 2022,
        techs: ['JavaScript', 'HTML & CSS'],
    },
    {
        id: 3,
        name: 'Airbnb-clone',
        previewImg: 'project1.png',
        link: 'https://poitrew.github.io/quizzical/',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam harum dignissimos, ipsa aspernatur assumenda perspiciatis tempore vero quas non! Commodi itaque, vero inventore assumenda voluptates in repudiandae non voluptatibus eum.',
        time: 2022,
        techs: ['React', 'React hooks', 'HTML & CSS'],
    },
]